# Generated by Django 5.0 on 2024-02-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('company', 'Company')], default='student', max_length=10),
        ),
    ]
