# Generated by Django 5.0 on 2024-01-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertype', '0002_alter_lastjob_end_date_alter_lastjob_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob',
            name='job_qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
