# Generated by Django 5.0 on 2024-02-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usertype', '0003_company_student_customuser_line_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='company',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studenteducation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentskill',
            name='student',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='StudentEducation',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='StudentSkill',
        ),
    ]
