# Generated by Django 5.0 on 2024-02-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertype', '0004_remove_companyprofile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='line_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
