# Generated by Django 5.0 on 2024-02-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentinfo",
            old_name="education",
            new_name="last_job",
        ),
        migrations.RenameField(
            model_name="studentinfo",
            old_name="intern_job",
            new_name="university",
        ),
        migrations.AddField(
            model_name="studentinfo",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentinfo",
            name="faculty",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="studentinfo",
            name="major",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
