# Generated by Django 5.0 on 2024-02-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="job",
            field=models.ManyToManyField(related_name="students", to="usertype.job"),
        ),
    ]
