# Generated by Django 5.0 on 2024-03-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyinfo",
            name="country",
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="intern_company",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="last_job",
            field=models.TextField(blank=True, null=True),
        ),
    ]
