# Generated by Django 5.0 on 2024-03-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0002_studentprofile_job"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StatusUser",
        ),
        migrations.RemoveField(
            model_name="companyprofile",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="company",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="job",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="status",
        ),
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("FINDING", "Finding"),
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("INTERVIEW", "Interview"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
