# Generated by Django 5.0 on 2024-03-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0003_job_company_id_alter_studentinfo_intern_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="company_id",
        ),
    ]
