# Generated by Django 5.0 on 2024-02-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0003_company_companyprofile_studentprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="student_id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
