# Generated by Django 5.0 on 2024-03-01 19:06

import django.contrib.auth.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0003_delete_statususer_remove_companyprofile_student_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("usertype.customuser",),
            managers=[
                ("admin", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="StudentInfo",
            field=models.ManyToManyField(
                related_name="companies", to="usertype.studentinfo"
            ),
        ),
        migrations.CreateModel(
            name="Matching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usertype.companyinfo",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="usertype.job"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usertype.studentinfo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="matching",
            field=models.ManyToManyField(
                related_name="companies", to="usertype.matching"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="matching",
            field=models.ManyToManyField(
                related_name="students", to="usertype.matching"
            ),
        ),
        migrations.DeleteModel(
            name="StudentAccpetOrNot",
        ),
    ]
