# Generated by Django 5.0 on 2024-03-21 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0004_remove_job_company_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usertype.companyinfo",
                    ),
                ),
                (
                    "job",
                    models.ManyToManyField(
                        related_name="companiesjob", to="usertype.job"
                    ),
                ),
            ],
        ),
    ]
