# Generated by Django 5.0 on 2024-03-01 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0004_admin_companyprofile_studentinfo_matching_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="StudentInfo",
        ),
        migrations.RemoveField(
            model_name="companyprofile",
            name="matching",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="matching",
        ),
        migrations.AddField(
            model_name="matching",
            name="interview",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                to="usertype.interview",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="matching",
            name="status",
            field=models.CharField(max_length=50),
        ),
    ]
