# Generated by Django 5.0 on 2024-02-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0004_alter_studentprofile_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
