# Generated by Django 5.0 on 2024-03-01 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0005_remove_companyprofile_studentinfo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usertype.companyinfo"
            ),
        ),
    ]
