# Generated by Django 5.0 on 2024-02-08 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        ("student", "0001_initial"),
        ("usertype", "0006_alter_customuser_password_alter_customuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="company_address",
        ),
        migrations.RemoveField(
            model_name="companyprofile",
            name="company_description",
        ),
        migrations.RemoveField(
            model_name="companyprofile",
            name="company_email",
        ),
        migrations.RemoveField(
            model_name="companyprofile",
            name="company_logo",
        ),
        migrations.RemoveField(
            model_name="companyprofile",
            name="company_name_eng",
        ),
        migrations.RemoveField(
            model_name="companyprofile",
            name="company_name_thai",
        ),
        migrations.RemoveField(
            model_name="companyprofile",
            name="company_phone",
        ),
        migrations.RemoveField(
            model_name="companyprofile",
            name="company_website",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="nick_name",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="student_id",
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="companyinfo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.companyinfo",
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=2,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="studentinfo",
            field=models.ForeignKey(
                default=82,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.studentinfo",
            ),
            preserve_default=False,
        ),
    ]
