# Generated by Django 5.0 on 2024-03-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0006_alter_job_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.CharField(max_length=255),
        ),
    ]
