# Generated by Django 5.0 on 2024-02-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0007_remove_companyprofile_company_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("COMPANY", "Company"),
                    ("ADMIN", "Admin"),
                ],
                max_length=50,
            ),
        ),
    ]
