# Generated by Django 5.0 on 2024-03-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0008_remove_job_city_remove_job_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="city",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="company",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="country",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
