# Generated by Django 5.0 on 2024-03-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0009_job_city_job_company_job_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matching",
            name="interview",
        ),
    ]
