# Generated by Django 5.0 on 2024-02-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0010_studentinfo_username"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentInfo",
        ),
    ]
