# Generated by Django 5.0 on 2024-03-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0010_remove_matching_interview"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="match",
            field=models.ManyToManyField(
                related_name="companies", to="usertype.matching"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="match",
            field=models.ManyToManyField(
                related_name="students", to="usertype.matching"
            ),
        ),
    ]
