# Generated by Django 5.0 on 2024-02-14 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0011_delete_studentinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "company_name_eng",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("company_name_thai", models.CharField(max_length=100)),
                ("logoc", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("foundation_date", models.DateField()),
                ("company_type", models.CharField(max_length=255)),
                ("number_of_employees", models.IntegerField()),
                ("website", models.URLField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("province", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=255)),
                ("address_label", models.CharField(max_length=255)),
                ("line_id", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                (
                    "profile",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                (
                    "student_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("nick_name", models.CharField(max_length=100)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=10)),
                ("line_id", models.CharField(max_length=200)),
                ("website", models.URLField()),
                ("cv", models.URLField()),
                ("last_job", models.CharField(max_length=200)),
                ("intern_des", models.CharField(max_length=200)),
                ("intern_company", models.CharField(max_length=200)),
                ("interest_job", models.CharField(max_length=200)),
                ("skill", models.CharField(max_length=200)),
                ("university", models.CharField(max_length=200)),
                ("faculty", models.CharField(blank=True, max_length=50)),
                ("major", models.CharField(blank=True, max_length=50)),
                ("gpa", models.CharField(max_length=10)),
                ("intern_start", models.DateField()),
                ("intern_end", models.DateField()),
                ("eng_skill", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="companyinfo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="usertype.companyinfo",
            ),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workplace", models.CharField(max_length=255)),
                ("worktype", models.CharField(max_length=255)),
                ("quality", models.CharField(max_length=255)),
                ("benefit", models.CharField(max_length=255)),
                ("workstart", models.TimeField()),
                ("workend", models.TimeField()),
                ("workday", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usertype.companyinfo",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="studentinfo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usertype.studentinfo"
            ),
        ),
    ]
