# Generated by Django 5.0 on 2024-03-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0011_companyprofile_match_studentprofile_match"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="match",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="match",
        ),
    ]
