# Generated by Django 5.0 on 2024-02-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0012_companyinfo_studentinfo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentinfo",
            name="gpa",
        ),
        migrations.RemoveField(
            model_name="studentinfo",
            name="website",
        ),
    ]
