# Generated by Django 5.0 on 2024-03-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0012_remove_companyprofile_match_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matching",
            name="status",
            field=models.CharField(max_length=255),
        ),
    ]
