# Generated by Django 5.0 on 2024-03-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0013_alter_matching_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="customuser",
            unique_together={("username",)},
        ),
    ]
