# Generated by Django 5.0 on 2024-02-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0013_remove_studentinfo_gpa_remove_studentinfo_website"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentinfo",
            name="intern_des",
        ),
    ]
