# Generated by Django 5.0 on 2024-03-04 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0014_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="interview",
        ),
        migrations.AddField(
            model_name="matching",
            name="interview",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="usertype.interview",
            ),
        ),
    ]
