# Generated by Django 5.0 on 2024-02-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0014_remove_studentinfo_intern_des"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companyinfo",
            old_name="city",
            new_name="district",
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="company_des",
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="phone",
            field=models.CharField(default=12, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="sub_district",
            field=models.CharField(default=34, max_length=255),
            preserve_default=False,
        ),
    ]
