# Generated by Django 5.0 on 2024-03-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0015_remove_companyprofile_interview_matching_interview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interview",
            name="company",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="status",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="student",
        ),
    ]
