# Generated by Django 5.0 on 2024-02-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0015_rename_city_companyinfo_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinfo",
            name="company_des",
            field=models.CharField(max_length=255),
        ),
    ]
