# Generated by Django 5.0 on 2024-03-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0016_remove_interview_company_remove_interview_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinfo",
            name="intern_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="intern_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
