# Generated by Django 5.0 on 2024-02-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0016_alter_companyinfo_company_des"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyinfo",
            name="address_label",
        ),
        migrations.RemoveField(
            model_name="companyinfo",
            name="company_type",
        ),
    ]
