# Generated by Django 5.0 on 2024-02-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0017_remove_companyinfo_address_label_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="workplace",
            new_name="Qualifications",
        ),
        migrations.AddField(
            model_name="job",
            name="Requirement",
            field=models.CharField(default=21, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="Skills",
            field=models.CharField(default=1212, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="jobdes",
            field=models.CharField(default=1212, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="jobname",
            field=models.CharField(default=1212, max_length=255),
            preserve_default=False,
        ),
    ]
