# Generated by Django 5.0 on 2024-03-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0018_rename_logoc_companyinfo_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="qualifications",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
