# Generated by Django 5.0 on 2024-02-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "usertype",
            "0018_rename_workplace_job_qualifications_job_requirement_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="usertype.companyprofile",
            ),
            preserve_default=False,
        ),
    ]
