# Generated by Django 5.0 on 2024-03-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0019_alter_job_qualifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinfo",
            name="interest_job",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="skill",
            field=models.TextField(),
        ),
    ]
