# Generated by Django 5.0 on 2024-02-15 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0019_alter_job_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="Qualifications",
            new_name="qualifications",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="Requirement",
            new_name="requirement",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="Skills",
            new_name="skills",
        ),
        migrations.RemoveField(
            model_name="job",
            name="company",
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="usertype.job",
            ),
        ),
    ]
