# Generated by Django 5.0 on 2024-03-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0020_alter_studentinfo_interest_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinfo",
            name="address",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="company_des",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="country",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="district",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="province",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="sub_district",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="benefit",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="jobdes",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="qualifications",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="quality",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="requirement",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="faculty",
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="intern_company",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="last_job",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="major",
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
