# Generated by Django 5.0 on 2024-02-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0020_rename_qualifications_job_qualifications_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyinfo",
            name="job",
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="jobs",
            field=models.ManyToManyField(related_name="companies", to="usertype.job"),
        ),
    ]
