# Generated by Django 5.0 on 2024-02-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0021_remove_companyinfo_job_companyinfo_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="city",
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="company",
            field=models.CharField(default=121, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="country",
            field=models.CharField(default=1212, max_length=255),
            preserve_default=False,
        ),
    ]
