# Generated by Django 5.0 on 2024-02-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0022_job_city_job_company_job_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinfo",
            name="logoc",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
