# Generated by Django 5.0 on 2024-02-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertype", "0023_alter_companyinfo_logoc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("location", models.CharField(max_length=255)),
                ("link", models.URLField()),
            ],
        ),
    ]
