# Generated by Django 5.0 on 2024-02-08 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "company_name_eng",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("company_name_thai", models.CharField(max_length=100)),
                ("logoc", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("foundation_date", models.DateField()),
                ("company_type", models.CharField(max_length=255)),
                ("number_of_employees", models.IntegerField()),
                ("website", models.URLField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("province", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=255)),
                ("address_label", models.CharField(max_length=255)),
                ("line_id", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workplace", models.CharField(max_length=255)),
                ("worktype", models.CharField(max_length=255)),
                ("quality", models.CharField(max_length=255)),
                ("benefit", models.CharField(max_length=255)),
                ("workstart", models.TimeField()),
                ("workend", models.TimeField()),
                ("workday", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.companyinfo",
                    ),
                ),
            ],
        ),
    ]
